wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.4
    framework: huggingface
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1711282378.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 1
      - 2
      - 3
      - 17
      - 23
      - 37
      4: 3.11.5
      5: 0.16.4
      8:
      - 1
      - 3
      - 5
      10:
      - 3
      13: windows-amd64
